### ISSUE TITLE
'.yaml' extension not supported on forwards 

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/crops#3]
#### Issue

In version 1.21.1, I can use a forward to an `ops.yaml` in another directory. Version 2.0.2 also supports `ops.yaml` when running in the same directory as the file.

But whenever I try to use a forward to another `ops.yaml`, I get an error saying `ops.yml` does not exist, and the action does not run. If I rename the second `ops.yaml` to `ops.yml`, it will work as normal.

#### Expected behaviour

Forwards work with an `ops.yaml` file in the target directory.

#### Affected versions

2.0.0.rc14 and later

#### Additional notes

In an older version, I may have gotten the error, but the action ran anyway. I can't reproduce this anymore.

##### `./ops.yaml` file
```yaml
forwards:
  dir: directory
```
`./directory/ops.yaml` exists and is a valid `ops.yaml` with dependencies and actions. No `ops.yml` files exist.

##### Attempting to run the action
```console
$ ops dir up
Forwarding 'ops up' to 'directory'...
File 'ops.yml' does not exist.
```

**Comment by nickthecook** [comment]
Thanks for the report.

Fixed in 2.0.4 via `brew` (or gem 2.0.4.rc1).
