### ISSUE TITLE
'ops init' checks for 'ops.yml' instead of 'ops.yaml'

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/crops#4]
**Version:** 2.0.6

`ops init` always tries to create `ops.yml` instead of `ops.yaml`. This happens even if you have an `ops.yaml` file—
it only checks for `ops.yml`.

#### Expected behaviour

* If `ops.yaml` exists, do not create `ops.yml`. Give the error saying `ops.yaml` already exists.
* If `ops.yml` exists, do not create `ops.yaml`. Give the error saying `ops.yml` already exists.
* If neither `ops.yaml` or `ops.yml` exist, create `ops.yaml`.
* If both `ops.yaml` and `ops.yml` exist, give the error saying `ops.yaml` already exists.
* If `ops` was invoked with the `-f`/`-file` option, error if said file already exists, and create the file otherwise.

**Comment by nickthecook** [comment]
`ops init` will error out if `ops.yaml` exists. I'm not going to change the default file from `ops.yml` to `ops.yaml`, so I'm not going to make the other changes.

At some point, I may add a way for the user to express a preference for `.yaml` over `.yml` and then `init` would take that into account.
