### ISSUE TITLE
Allow defined 'init' actions to override the built-in

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/crops#5]
#### Current behaviour

You can't create `ops init` actions because it is a built-in.

#### Desired behaviour

Defining an `ops init` action is treated like any other action.

#### Rationale

`init` is a common keyword that might be used with `ops`, but `ops init` is only useful once per project, if ever; it doesn't serve any purpose once `ops.yaml` exists.

If an `ops init` action is defined, then the `ops.yaml` file already exists! So at that point `ops init` can no longer serve its built-in purpose.

**Comment by ErikHumphrey** [comment]
Related to https://github.com/nickthecook/crops/issues/4

**Comment by nickthecook** [comment]
Fixed in 2.1.1. Actions override builtins.
